/* ── ARTCANVAS DEMO DATA ────────────────────────────────── */

window.AC_ARTISTS = [
  {id:1,  name:'NightVision',    tagline:'Sci-fi concept artist · 12 years professional', followers:'48.2K', seed:50},
  {id:2,  name:'DragonScale',    tagline:'Fantasy illustrator & world builder',            followers:'31.7K', seed:80},
  {id:3,  name:'PrismStudio',    tagline:'Abstract generative & digital painter',          followers:'67.4K', seed:30},
  {id:4,  name:'GhostBrush',     tagline:'Dark portraits · horror · psychological art',   followers:'22.9K', seed:60},
  {id:5,  name:'CosmicInk',      tagline:'Space art · nebulae · astronomical paintings',  followers:'55.1K', seed:100},
  {id:6,  name:'IronForge',      tagline:'Mecha design · hard sci-fi · concept art',      followers:'29.6K', seed:170},
  {id:7,  name:'WillowMist',     tagline:'Nature · forest fantasy · peaceful art',        followers:'19.3K', seed:140},
  {id:8,  name:'EmberCraft',     tagline:'Fire · elemental · mythological art',           followers:'14.8K', seed:20},
  {id:9,  name:'CrystalDepths',  tagline:'Gem art · luminescent caves · surrealism',      followers:'11.2K', seed:200},
  {id:10, name:'NeonPulse',      tagline:'Cyberpunk · neon city · dystopian future',      followers:'72.6K', seed:260},
  {id:11, name:'ArcaneQuill',    tagline:'Spell art · runic designs · magical realism',   followers:'18.4K', seed:35},
  {id:12, name:'VoidWalker',     tagline:'Dark space · existential · surreal cosmos',     followers:'24.8K', seed:90},
  {id:13, name:'SilverThread',   tagline:'Ethereal portraits · silver & gold palette',    followers:'16.1K', seed:155},
  {id:14, name:'TitanForge',     tagline:'Epic landscapes · colossal creatures',          followers:'33.5K', seed:220},
  {id:15, name:'PixelSorcerer',  tagline:'AI-assisted art · generative dreams',           followers:'41.9K', seed:75},
  {id:16, name:'MidnightCoral',  tagline:'Underwater fantasy · bioluminescence',          followers:'13.7K', seed:310},
  {id:17, name:'CrimsonArrow',   tagline:'Action concept · dynamic poses · warriors',     followers:'27.2K', seed:15},
  {id:18, name:'FrostlineArt',   tagline:'Ice & snow · Nordic mythology · cold beauty',  followers:'20.8K', seed:185},
  {id:19, name:'SolsticeInk',    tagline:'Sacred geometry · mandalas · cosmic patterns',  followers:'38.6K', seed:250},
  {id:20, name:'ObsidianWing',   tagline:'Dark fantasy · fallen angels · epic drama',     followers:'45.3K', seed:120},
];

window.AC_WORKS = [
  // ── TOP TIER (most liked) ──────────────────────────
  {id:1,  artistId:10, title:'Neon Rain',              style:'neon',     category:'dark',      tags:['neon','cyberpunk','city','rain'],                    likes:24870, views:'142K', desc:'Midnight downpour in a district nobody names anymore. Every surface a screen. Every screen a lie. Shot on location in my imagination.'},
  {id:2,  artistId:2,  title:'Dragon of the Abyss',   style:'dragon',   category:'fantasy',   tags:['dragon','fantasy','abyss','epic'],                   likes:21340, views:'128K', desc:'The Ancient of Deeps surfaces for the first time in a thousand years. Six months of work. My proudest piece.'},
  {id:3,  artistId:5,  title:'Nebula Born',            style:'space',    category:'sci-fi',    tags:['space','nebula','stars','cosmic'],                   likes:18920, views:'114K', desc:'A star system ignites from the swirling chaos of a newborn nebula. Third in my Void Series.'},
  {id:4,  artistId:20, title:'Fallen Seraph',          style:'portrait', category:'character', tags:['angel','dark','fallen','portrait'],                  likes:17650, views:'108K', desc:'She chose the fall. Not because she had to. Because she wanted to know what it felt like.'},
  {id:5,  artistId:15, title:'Dream Architecture',     style:'flow',     category:'abstract',  tags:['ai','generative','abstract','dreamscape'],            likes:16200, views:'99.1K', desc:'AI-assisted piece exploring the boundary between intention and emergence. The algorithm surprised me here.'},
  {id:6,  artistId:6,  title:'Iron Sentinel',          style:'mecha',    category:'sci-fi',    tags:['mecha','robot','armor','sentinel'],                  likes:15780, views:'95.3K', desc:'Guardian unit designed for hostile terrain. The hexagonal plating distributes kinetic impact across the full exoskeleton.'},
  {id:7,  artistId:3,  title:'Chromatic Interference', style:'flow',     category:'abstract',  tags:['abstract','color','waves','generative'],             likes:14330, views:'87.6K', desc:'Eight sine-wave fields collide at slightly different frequencies. The color emerges — it is not designed.'},
  {id:8,  artistId:12, title:'The Void Between',       style:'space',    category:'sci-fi',    tags:['space','void','dark','cosmos'],                      likes:13890, views:'83.2K', desc:'What exists between galaxies? I went looking. This is what I found. Or what found me.'},
  {id:9,  artistId:4,  title:'The Watcher',            style:'portrait', category:'character', tags:['portrait','dark','eyes','character'],                likes:12760, views:'78.4K', desc:'She has seen things most minds could not contain. A study in controlled emotion and geometric light.'},
  {id:10, artistId:14, title:'Colossus at the Gate',   style:'dragon',   category:'fantasy',   tags:['dragon','epic','colossus','gate'],                   likes:11940, views:'73.1K', desc:'The last gate. The last guardian. He has stood here for ten thousand years and will stand ten thousand more.'},

  // ── HIGH TIER ──────────────────────────────────────
  {id:11, artistId:2,  title:'Serpent King',           style:'dragon',   category:'fantasy',   tags:['dragon','sea','serpent','king'],                     likes:10820, views:'67.5K', desc:'Ancient sea serpent surfaces in the harbor at dawn. Barnacles and coral encrusting scales the size of city blocks.'},
  {id:12, artistId:10, title:'Midnight Circuit',       style:'neon',     category:'dark',      tags:['neon','circuit','cyberpunk','dark'],                 likes:10100, views:'63.2K', desc:'The city never sleeps — it just changes channels. A look inside the infrastructure layer most never see.'},
  {id:13, artistId:6,  title:'Unit 7 Protocol',        style:'mecha',    category:'concept',   tags:['mecha','robot','protocol','military'],               likes:9870,  views:'61.4K', desc:'Combat recon unit with adaptive armor panels. Designed against a destroyed-city backdrop for scale.'},
  {id:14, artistId:5,  title:'Aurora Station',         style:'space',    category:'sci-fi',    tags:['space','aurora','station','orbit'],                  likes:9540,  views:'59.8K', desc:'Atmospheric ionization creates impossible colors in the upper stratosphere. Observed from polar orbit.'},
  {id:15, artistId:20, title:'Wings of the Condemned', style:'dragon',   category:'dark',      tags:['dark','wings','fallen','epic'],                      likes:9210,  views:'57.3K', desc:'Not a monster. Not a hero. Something more dangerous — a being who has abandoned the distinction entirely.'},
  {id:16, artistId:19, title:'Sacred Mandala VII',     style:'flow',     category:'abstract',  tags:['mandala','sacred','geometry','cosmic'],              likes:8960,  views:'55.1K', desc:'Seventh in the Sacred Geometry series. Each rotation hides a different message for whoever is patient enough to find it.'},
  {id:17, artistId:8,  title:'Ember Storm',            style:'fire',     category:'dark',      tags:['fire','storm','elemental','intense'],                likes:8730,  views:'53.7K', desc:'Not destruction — transformation. Fire as the great equalizer. Part of my Elemental Fury series.'},
  {id:18, artistId:7,  title:'Moonlit Grove',          style:'forest',   category:'fantasy',   tags:['forest','moon','bioluminescent','nature'],           likes:8450,  views:'52.2K', desc:'Bioluminescent mushrooms and fireflies light a path through the ancient pines. Inspired by old-growth rainforests.'},
  {id:19, artistId:9,  title:'Deep Cavern',            style:'crystal',  category:'fantasy',   tags:['crystal','cave','gems','underground'],               likes:8120,  views:'50.8K', desc:'A forgotten cave system beneath the mountains. Walls encrusted with formations that emit their own cold light.'},
  {id:20, artistId:11, title:'Arcane Inscription',     style:'neon',     category:'fantasy',   tags:['magic','rune','arcane','glow'],                     likes:7840,  views:'49.1K', desc:'Ancient runic language reinterpreted through a neon lens. The spell still works. I checked.'},

  // ── MID TIER ───────────────────────────────────────
  {id:21, artistId:15, title:'Synthetic Forest',       style:'forest',   category:'abstract',  tags:['ai','forest','synthetic','dreamscape'],             likes:7620,  views:'47.8K', desc:'What would a forest look like if dreamed by an AI that had only read about trees? Exactly like this.'},
  {id:22, artistId:13, title:'Silver Reverie',         style:'portrait', category:'character', tags:['portrait','silver','ethereal','beauty'],            likes:7390,  views:'46.3K', desc:'A character study in silver and shadow. The palette emerged from a single color choice: cool white as warm light.'},
  {id:23, artistId:2,  title:'Forest Dragon',          style:'dragon',   category:'fantasy',   tags:['dragon','forest','guardian','green'],               likes:7140,  views:'44.9K', desc:'The guardian of the old growth canopy. She is older than the oldest tree and will outlast the last.'},
  {id:24, artistId:17, title:'Last Stand',             style:'mecha',    category:'concept',   tags:['warrior','mecha','battle','action'],                likes:6890,  views:'43.5K', desc:'One unit. A thousand enemies. The math does not favor heroism. The heart does not care about math.'},
  {id:25, artistId:5,  title:'Gravity Well',           style:'space',    category:'sci-fi',    tags:['space','blackhole','gravity','cosmos'],              likes:6650,  views:'41.8K', desc:'Light bending around a stellar-mass object. Not a black hole — something stranger. Best gravitational lensing work I\'ve done.'},
  {id:26, artistId:10, title:'Neon District',          style:'neon',     category:'dark',      tags:['neon','city','cyberpunk','district'],               likes:6420,  views:'40.6K', desc:'Block 7, sector unknown. Every surface a screen, every screen a lie. Welcome to the District.'},
  {id:27, artistId:4,  title:'Shadow Self',            style:'portrait', category:'character', tags:['portrait','shadow','dark','duality'],               likes:6180,  views:'38.9K', desc:'We all carry a version of ourselves we don\'t show the world. This is mine. Warm light front. Cold truth behind.'},
  {id:28, artistId:16, title:'Deep Sea Neon',          style:'neon',     category:'abstract',  tags:['underwater','neon','bioluminescent','ocean'],       likes:5940,  views:'37.4K', desc:'What if the deep ocean was a cyberpunk city? I spent three weeks on the lighting alone.'},
  {id:29, artistId:18, title:'Frost Giant',            style:'dragon',   category:'fantasy',   tags:['frost','giant','nordic','fantasy'],                 likes:5720,  views:'36.2K', desc:'Norse mythology meets hard fantasy. The frost giant doesn\'t know we are watching. That is perhaps the only reason we are still alive.'},
  {id:30, artistId:3,  title:'Wavelength',             style:'flow',     category:'abstract',  tags:['abstract','frequency','waves','color'],             likes:5480,  views:'34.7K', desc:'Color as vibration. Each hue occupies its own frequency band in this interference study.'},

  // ── REGULAR TIER ───────────────────────────────────
  {id:31, artistId:9,  title:'Crystal Lattice',        style:'crystal',  category:'fantasy',   tags:['crystal','lattice','geometry','light'],             likes:5240,  views:'33.2K', desc:'Perfect geometric formations growing from a fractured cave floor. Refracts every color of the spectrum.'},
  {id:32, artistId:8,  title:'Phoenix Hour',           style:'fire',     category:'dark',      tags:['fire','phoenix','rebirth','myth'],                  likes:5010,  views:'31.9K', desc:'Every ending carries its next beginning inside it. Fire as metaphor. Fire as fact.'},
  {id:33, artistId:14, title:'Mountain Titan',         style:'dragon',   category:'fantasy',   tags:['dragon','mountain','titan','ancient'],              likes:4790,  views:'30.5K', desc:'The mountain was never a mountain. It was always sleeping. Last week it stopped sleeping.'},
  {id:34, artistId:1,  title:'Cold Horizon',           style:'space',    category:'sci-fi',    tags:['space','planet','horizon','orbit'],                 likes:4560,  views:'29.1K', desc:'A gas giant looms over the frozen plains of its outermost moon. The ring system scatters light in ways no camera can capture.'},
  {id:35, artistId:11, title:'Spell Fragment',         style:'crystal',  category:'fantasy',   tags:['magic','crystal','spell','fragment'],               likes:4330,  views:'27.8K', desc:'What remains of a spell after it\'s been cast. Not nothing. Something crystalline and permanent and beautiful.'},
  {id:36, artistId:19, title:'Resonance Field',        style:'flow',     category:'abstract',  tags:['resonance','field','energy','abstract'],            likes:4110,  views:'26.3K', desc:'Two frequencies, perfectly matched, amplifying each other into something larger than either alone.'},
  {id:37, artistId:12, title:'Event Horizon',          style:'space',    category:'sci-fi',    tags:['space','blackhole','horizon','dark'],               likes:3890,  views:'24.9K', desc:'The point of no return. Everything beyond here is theory. I went anyway.'},
  {id:38, artistId:13, title:'Gilded Portrait',        style:'portrait', category:'character', tags:['portrait','gold','elegant','character'],            likes:3680,  views:'23.6K', desc:'A commission piece reworked with permission. The subject wanted gold. Gold is what they got.'},
  {id:39, artistId:20, title:'The Divide',             style:'space',    category:'sci-fi',    tags:['space','divide','dark','epic'],                     likes:3460,  views:'22.1K', desc:'On one side: everything we know. On the other: everything we\'ve been afraid to know.'},
  {id:40, artistId:7,  title:'Ancient Pines',          style:'forest',   category:'fantasy',   tags:['forest','pines','night','ancient'],                 likes:3240,  views:'20.8K', desc:'Thousand-year-old pines stand silent in the blue hour. An homage to the forests I grew up in.'},
  {id:41, artistId:17, title:'The Duel',               style:'fire',     category:'dark',      tags:['fire','duel','warriors','action'],                  likes:3020,  views:'19.4K', desc:'Two styles of fire, two schools of thought, two fighters. The outcome depends on who wants it more.'},
  {id:42, artistId:6,  title:'Colossus Rising',        style:'mecha',    category:'concept',   tags:['mecha','colossus','titan','rising'],                likes:2810,  views:'18.1K', desc:'Titan-class siege unit activating for the first time in decades. Scale achieved through layered destroyed architecture.'},
  {id:43, artistId:16, title:'Coral Cathedral',        style:'crystal',  category:'fantasy',   tags:['coral','ocean','cathedral','underwater'],           likes:2600,  views:'16.7K', desc:'Deep reef formations that took two thousand years to grow. I wanted to show them before they are gone.'},
  {id:44, artistId:15, title:'Neural Garden',          style:'forest',   category:'abstract',  tags:['ai','neural','garden','generative'],               likes:2390,  views:'15.3K', desc:'What a neural network sees when it dreams of nature. Structured chaos. Controlled wildness.'},
  {id:45, artistId:1,  title:'Void Station',           style:'mecha',    category:'sci-fi',    tags:['mecha','station','space','deep'],                   likes:2190,  views:'14.1K', desc:'Deep space relay platform designed for 200-year unmanned operation. Nothing human remains. Everything machine endures.'},
  {id:46, artistId:18, title:'Ice Cathedral',          style:'crystal',  category:'fantasy',   tags:['ice','cathedral','frost','nordic'],                 likes:1980,  views:'12.7K', desc:'A glacier that carved itself into the shape of devotion over ten thousand years. Natural architecture at its most extreme.'},
  {id:47, artistId:4,  title:'Fracture Line',          style:'portrait', category:'character', tags:['portrait','fracture','dark','broken'],              likes:1780,  views:'11.4K', desc:'The places we break are where the light gets in. Or out. Depends on the day.'},
  {id:48, artistId:9,  title:'Gem Heart',              style:'crystal',  category:'fantasy',   tags:['crystal','gem','heart','glow'],                     likes:1590,  views:'10.2K', desc:'A formation so perfect it could only be grown, not carved. Found untouched for millennia.'},
  {id:49, artistId:7,  title:'Lantern Wood',           style:'forest',   category:'fantasy',   tags:['forest','lantern','fairy','night'],                 likes:1400,  views:'9.1K',  desc:'Lost travelers follow the lantern lights deeper into the wood. They never wonder who lit them.'},
  {id:50, artistId:8,  title:'Inferno Core',           style:'fire',     category:'dark',      tags:['fire','inferno','core','intense'],                  likes:1220,  views:'7.9K',  desc:'The center of a fire column reaches temperatures that melt stone. Everything here is truth and nothing else.'},
  {id:51, artistId:11, title:'Runic Storm',            style:'neon',     category:'fantasy',   tags:['rune','storm','magic','glow'],                      likes:1050,  views:'6.8K',  desc:'When a runic inscription activates in a thunderstorm, this is what it looks like from the inside.'},
  {id:52, artistId:19, title:'Stellar Mandala',        style:'space',    category:'abstract',  tags:['mandala','space','stars','sacred'],                 likes:890,   views:'5.8K',  desc:'Sacred geometry mapped onto the night sky. Everything is pattern. Everything is intention.'},
  {id:53, artistId:3,  title:'Frequency',              style:'flow',     category:'abstract',  tags:['frequency','abstract','wave','signal'],             likes:740,   views:'4.8K',  desc:'Signal theory as visual art. Where waveforms intersect, new information emerges from the noise.'},
  {id:54, artistId:13, title:'The Observer',           style:'portrait', category:'character', tags:['portrait','observer','gaze','character'],           likes:590,   views:'3.9K',  desc:'She has watched every empire rise and every empire end. She is tired of watching. Something is about to change.'},
  {id:55, artistId:5,  title:'Starfall Drift',         style:'space',    category:'sci-fi',    tags:['space','starfall','drift','cosmic'],                likes:450,   views:'2.9K',  desc:'The moment before a star collapses — a meditation on scale and silence. Second in the Void Series.'},
  {id:56, artistId:2,  title:'Elder Flame',            style:'dragon',   category:'fantasy',   tags:['dragon','fire','elder','ancient'],                  likes:320,   views:'2.1K',  desc:'The eldest of the fire kin has forgotten more wars than humans have ever fought. Her breath is a geological event.'},
  {id:57, artistId:10, title:'Signal Lost',            style:'neon',     category:'sci-fi',    tags:['neon','signal','lost','city'],                      likes:210,   views:'1.4K',  desc:'Communication array in a city that stopped answering. The signs still flash old messages to an empty street.'},
  {id:58, artistId:14, title:'Ash and Iron',           style:'fire',     category:'dark',      tags:['fire','iron','dark','aftermath'],                   likes:140,   views:'970',   desc:'After the battle. After the fire. What remains is not loss — it is the raw material of the next thing.'},
  {id:59, artistId:12, title:'Deep Cold',              style:'space',    category:'sci-fi',    tags:['space','cold','deep','stars'],                      likes:90,    views:'620',   desc:'First post. I have been working up to this for two years. Here we go.'},
  {id:60, artistId:16, title:'First Light',            style:'forest',   category:'fantasy',   tags:['forest','light','new','debut'],                     likes:60,    views:'410',   desc:'New here! This is my debut piece. Forest dawn — the moment just before the world wakes up.'},
];

window.AC_COMMENTS = {
  1: [
    {user:'DragonScale',    text:'The wet street reflections are something else. How did you achieve that depth?',               hue:80},
    {user:'GhostBrush',     text:'This is the piece that made me join ArtCanvas. Seriously.',                                   hue:60},
    {user:'CosmicInk',      text:'The color temperature shift between the warm neon and the cold rain is masterclass.',         hue:100},
    {user:'SilverThread',   text:'I\'ve studied this piece for an hour trying to understand the lighting. Incredible.',         hue:155},
    {user:'NightVision',    text:'NeonPulse never misses. This might be your best yet.',                                       hue:50},
    {user:'PixelSorcerer',  text:'The fact that this was done without 3D is still blowing my mind.',                           hue:75},
  ],
  2: [
    {user:'PrismStudio',    text:'Absolutely breathtaking. The scale of those wings reads perfectly.',                          hue:30},
    {user:'NightVision',    text:'Easily the best dragon piece I\'ve seen this year. Six months? It shows.',                   hue:50},
    {user:'CosmicInk',      text:'The fire breath coloring — those purple tones mixed with orange — is next level.',           hue:100},
    {user:'EmberCraft',     text:'As someone who paints a lot of fire, your flame work here is technically flawless.',          hue:20},
    {user:'ObsidianWing',   text:'I study dragon anatomy for my own work. You nailed the wing membrane structure.',            hue:120},
    {user:'TitanForge',     text:'The cave atmosphere framing this is what elevates it from great to legendary.',              hue:220},
  ],
  3: [
    {user:'VoidWalker',     text:'The nebula gradients feel physically real. What blending mode?',                             hue:90},
    {user:'PrismStudio',    text:'That star field has three visible depth layers. Wild detail.',                               hue:30},
    {user:'IronForge',      text:'Space art done right. The gas giant rings catch the light exactly as they should.',          hue:170},
    {user:'MidnightCoral',  text:'The color palette here would work perfectly underwater too. Stunning choices.',              hue:310},
  ],
  4: [
    {user:'GhostBrush',     text:'The lighting choice on a fallen angel is everything. Cold from above. Nothing from God.',    hue:60},
    {user:'SilverThread',   text:'ObsidianWing portraits are always a journey. This one especially.',                         hue:155},
    {user:'ArcaneQuill',    text:'The wing feather detail in the shadows — I had to zoom in three times.',                    hue:35},
    {user:'CrimsonArrow',   text:'Character work that hits hard. The expression says everything the title implies.',           hue:15},
  ],
  6: [
    {user:'CosmicInk',      text:'The hexagonal armor is a genius design choice — practical and beautiful.',                   hue:100},
    {user:'GhostBrush',     text:'That glowing eye in the shadow background is haunting me.',                                  hue:60},
    {user:'NightVision',    text:'IronForge sets the standard for mecha design on this platform.',                             hue:50},
    {user:'VoidWalker',     text:'I love when technical rigor and artistic vision overlap. This is that.',                    hue:90},
  ],
  9: [
    {user:'CosmicInk',      text:'The split lighting technique you use is something I\'ve been trying to learn for months.',  hue:100},
    {user:'ObsidianWing',   text:'The eyes in this portrait tell the full story. No caption needed.',                         hue:120},
    {user:'DragonScale',    text:'GhostBrush does portraiture like nobody else on this site.',                                hue:80},
    {user:'PixelSorcerer',  text:'The color temperature control here — warm eye, cold temple — is so intentional. Love it.',  hue:75},
  ],
  11: [
    {user:'EmberCraft',     text:'Serpent at dawn is a concept I\'ve wanted to tackle. You beat me to it and crushed it.',    hue:20},
    {user:'WillowMist',     text:'The barnacle and coral detail is extraordinary. How long did the texture pass take?',       hue:140},
    {user:'NeonPulse',      text:'DragonScale\'s creature work is consistently the best on ArtCanvas. No argument.',          hue:260},
  ],
  17: [
    {user:'CrystalDepths',  text:'The ember scatter in the upper third is stunning compositionally.',                         hue:200},
    {user:'WillowMist',     text:'Fire as transformation — the piece earns that reading completely.',                         hue:140},
    {user:'FrostlineArt',   text:'Ironic that a frost artist is this obsessed with your fire work. It\'s just that good.',   hue:185},
  ],
  18: [
    {user:'WillowMist',     text:'This is exactly the energy I was hoping someone on this platform would capture.',           hue:140},
    {user:'MidnightCoral',  text:'The bioluminescent orbs feel like deep sea life translated to forest. Love the crossover.', hue:310},
    {user:'FrostlineArt',   text:'The moon through the pines is doing so much for the atmosphere.',                           hue:185},
  ],
  20: [
    {user:'ArcaneQuill',    text:'I studied rune systems for a year. You\'ve captured the visual grammar perfectly.',         hue:35},
    {user:'NightVision',    text:'The neon-rune fusion feels fresh. This is a lane nobody else is working in.',              hue:50},
    {user:'SolsticeInk',    text:'Sacred geometry meets arcane magic. This is my exact aesthetic. Favorited immediately.',   hue:250},
  ],
  7: [
    {user:'NightVision',    text:'The color mathematics in this piece are extraordinary. Genuine wonder.',                    hue:50},
    {user:'IronForge',      text:'I love when you can feel the algorithm underneath the surface of the art.',                 hue:170},
    {user:'SolsticeInk',    text:'Wave interference as art — this is what I\'ve been trying to articulate in my geometry work.', hue:250},
    {user:'PixelSorcerer',  text:'Generative work that transcends its process. This is art first, code second.',             hue:75},
  ],
};
