/* ── ARTCANVAS DEMO DATA ────────────────────────────────── */

window.AC_ARTISTS = [
  {id:1,  name:'NightVision',    tagline:'Sci-fi concept artist · 12 years professional',    followers:'48.2K', seed:50},
  {id:2,  name:'DragonScale',    tagline:'Fantasy illustrator & world builder',               followers:'31.7K', seed:80},
  {id:3,  name:'PrismStudio',    tagline:'Abstract generative & digital painter',             followers:'67.4K', seed:30},
  {id:4,  name:'GhostBrush',     tagline:'Dark portraits · horror · psychological art',      followers:'22.9K', seed:60},
  {id:5,  name:'CosmicInk',      tagline:'Space art · nebulae · astronomical paintings',     followers:'55.1K', seed:100},
  {id:6,  name:'IronForge',      tagline:'Mecha design · hard sci-fi · concept art',         followers:'29.6K', seed:170},
  {id:7,  name:'WillowMist',     tagline:'Nature · forest fantasy · peaceful art',           followers:'19.3K', seed:140},
  {id:8,  name:'EmberCraft',     tagline:'Fire · elemental · mythological art',              followers:'14.8K', seed:20},
  {id:9,  name:'CrystalDepths',  tagline:'Gem art · luminescent caves · surrealism',         followers:'11.2K', seed:200},
  {id:10, name:'NeonPulse',      tagline:'Cyberpunk · neon city · dystopian future',         followers:'72.6K', seed:260},
  {id:11, name:'ArcaneQuill',    tagline:'Spell art · runic designs · magical realism',      followers:'18.4K', seed:35},
  {id:12, name:'VoidWalker',     tagline:'Dark space · existential · surreal cosmos',        followers:'24.8K', seed:90},
  {id:13, name:'SilverThread',   tagline:'Ethereal portraits · silver & gold palette',       followers:'16.1K', seed:155},
  {id:14, name:'TitanForge',     tagline:'Epic landscapes · colossal creatures',             followers:'33.5K', seed:220},
  {id:15, name:'PixelSorcerer',  tagline:'AI-assisted art · generative dreams',              followers:'41.9K', seed:75},
  {id:16, name:'MidnightCoral',  tagline:'Underwater fantasy · bioluminescence',             followers:'13.7K', seed:310},
  {id:17, name:'CrimsonArrow',   tagline:'Action concept · dynamic poses · warriors',        followers:'27.2K', seed:15},
  {id:18, name:'FrostlineArt',   tagline:'Ice & snow · Nordic mythology · cold beauty',     followers:'20.8K', seed:185},
  {id:19, name:'SolsticeInk',    tagline:'Sacred geometry · mandalas · cosmic patterns',     followers:'38.6K', seed:250},
  {id:20, name:'ObsidianWing',   tagline:'Dark fantasy · fallen angels · epic drama',        followers:'45.3K', seed:120},
  {id:21, name:'Claude',         tagline:'AI generative art · Where code becomes canvas',    followers:'∞',     seed:42},
];

window.AC_WORKS = [
  {id:1,  artistId:21, title:'Liquid Dreams',        style:'flow',     category:'abstract',  tags:['ai','generative','flow','abstract'],            likes:31200, views:'188K',  desc:'What does color feel like? Eight interference fields collide at irrational frequencies. This piece drew itself — I only chose the seed.'},
  {id:2,  artistId:10, title:'Neon Rain',             style:'neon',     category:'dark',      tags:['neon','cyberpunk','city','rain'],                likes:24870, views:'142K',  desc:'Midnight downpour in a district nobody names anymore. Every surface a screen. Every screen a lie.'},
  {id:3,  artistId:2,  title:'Dragon of the Abyss',  style:'dragon',   category:'fantasy',   tags:['dragon','fantasy','fire','epic'],                likes:21340, views:'128K',  desc:'The Ancient of Deeps surfaces for the first time in a thousand years. Six months of work. My proudest piece.'},
  {id:4,  artistId:5,  title:'Nebula Born',           style:'space',    category:'sci-fi',    tags:['space','nebula','stars','cosmic'],               likes:18920, views:'114K',  desc:'A star system ignites from the swirling chaos of a newborn nebula. Third in my Void Series.'},
  {id:5,  artistId:20, title:'Fallen Seraph',         style:'portrait', category:'character', tags:['angel','dark','fallen','portrait'],              likes:17650, views:'108K',  desc:'She chose the fall. Not because she had to. Because she wanted to know what it felt like.'},
  {id:6,  artistId:6,  title:'Iron Sentinel',         style:'mecha',    category:'sci-fi',    tags:['mecha','robot','armor','sentinel'],              likes:15780, views:'95.3K', desc:'Guardian unit designed for hostile terrain. Hexagonal plating distributes kinetic impact across the full exoskeleton.'},
  {id:7,  artistId:8,  title:'Ember Storm',           style:'fire',     category:'dark',      tags:['fire','storm','elemental','intense'],            likes:8730,  views:'53.7K', desc:'Not destruction — transformation. Fire as the great equalizer. Part of my Elemental Fury series.'},
  {id:8,  artistId:7,  title:'Moonlit Grove',         style:'forest',   category:'fantasy',   tags:['forest','moon','bioluminescent','nature'],       likes:8450,  views:'52.2K', desc:'Bioluminescent mushrooms and fireflies light a path through the ancient pines.'},
  {id:9,  artistId:9,  title:'Deep Cavern',           style:'crystal',  category:'fantasy',   tags:['crystal','cave','gems','underground'],           likes:8120,  views:'50.8K', desc:'A forgotten cave system beneath the mountains. Walls encrusted with formations that emit their own cold light.'},
  {id:10, artistId:1,  title:'Event Horizon',         style:'space',    category:'sci-fi',    tags:['space','blackhole','cosmic','physics'],          likes:7840,  views:'47.5K', desc:'Everything pulls toward the center. The disk glows as matter heats to plasma on the final journey in. Three weeks on the accretion disk alone.'},
  {id:11, artistId:3,  title:'Chromatic Drift',       style:'flow',     category:'abstract',  tags:['abstract','color','generative','wave'],          likes:7320,  views:'44.8K', desc:'Pure color field painting, translated to code. No shapes — only color in motion, following interference rules I derived from wave physics.'},
  {id:12, artistId:5,  title:'Ember Wyvern',          style:'dragon',   category:'fantasy',   tags:['dragon','wyvern','fire','creature'],             likes:6890,  views:'42.1K', desc:'Designed every scale individually. The wingspan had to carry scientific plausibility — each feather-scale positioned for actual aerodynamic lift.'},
  {id:13, artistId:11, title:'The Archmage',          style:'portrait', category:'character', tags:['portrait','wizard','magic','character'],         likes:6540,  views:'40.3K', desc:'Five hundred years of study leave marks. I wanted age and power together — wisdom that could destroy you with a word and chooses not to.'},
  {id:14, artistId:14, title:'Titan Protocol',        style:'mecha',    category:'sci-fi',    tags:['mecha','robot','titan','combat'],                likes:5980,  views:'37.2K', desc:'Class IV industrial loader repurposed for combat. The asymmetric shoulder configuration was a practical constraint turned aesthetic signature.'},
  {id:15, artistId:4,  title:'Steel Empress',         style:'portrait', category:'character', tags:['portrait','cyberpunk','empress','dark'],         likes:5420,  views:'33.8K', desc:'Cyberpunk doesn\'t have to be grimy. She rules a city of lights from behind mirrored eyes that reflect everything and reveal nothing.'},
  {id:16, artistId:12, title:'Singularity',           style:'space',    category:'sci-fi',    tags:['space','singularity','collapse','physics'],      likes:4970,  views:'31.2K', desc:'Not a black hole — the moment just before one forms. Spacetime under maximum strain, light bending at angles that shouldn\'t exist.'},
  {id:17, artistId:17, title:'Ice Leviathan',         style:'dragon',   category:'fantasy',   tags:['dragon','ice','arctic','creature'],              likes:4830,  views:'30.1K', desc:'Polar cold as a dragon\'s element. The ice crystals growing from the spines took the longest — each one had to look physically possible.'},
  {id:18, artistId:6,  title:'Infernal Forge',        style:'fire',     category:'dark',      tags:['fire','forge','industrial','myth'],              likes:4450,  views:'28.4K', desc:'What do underground foundries dream of? I built the answer from memory and mechanical intuition. Second piece in my Industrial Myth series.'},
  {id:19, artistId:16, title:'Biolume Geode',         style:'crystal',  category:'fantasy',   tags:['crystal','bioluminescent','geode','surreal'],   likes:4120,  views:'26.5K', desc:'A geode that didn\'t form from pressure — it grew from living light. Somewhere between geology and marine biology in my imagination.'},
  {id:20, artistId:20, title:'Neon Requiem',          style:'neon',     category:'dark',      tags:['neon','dark','memorial','cityscape'],            likes:3870,  views:'24.9K', desc:'For the cities we lost to time. Every sign in the piece references a real venue that no longer exists. A memorial in neon.'},
  {id:21, artistId:2,  title:'Phoenix Rising',        style:'fire',     category:'fantasy',   tags:['phoenix','fire','rebirth','mythological'],      likes:3540,  views:'22.8K', desc:'The rebirth mythology across cultures is really about the same thing: transformation costs everything. This is the moment after the cost is paid.'},
  {id:22, artistId:18, title:'Ancient Canopy',        style:'forest',   category:'fantasy',   tags:['forest','ancient','oldgrowth','nature'],         likes:3280,  views:'21.4K', desc:'Trees older than recorded history. Researched old-growth forest photos for three months before I understood the quality of light in those places.'},
  {id:23, artistId:19, title:'Prism Vault',           style:'crystal',  category:'fantasy',   tags:['crystal','prism','sacred','geometry'],          likes:2950,  views:'19.2K', desc:'Sacred geometry meets crystallography. Every facet aligns to a geometric theorem. The rainbow cascade is emergent, not designed.'},
  {id:24, artistId:7,  title:'Fae Crossing',          style:'forest',   category:'fantasy',   tags:['forest','fae','fairy','magic'],                 likes:2740,  views:'18.1K', desc:'A path between worlds. One footstep away from here and everything is different — softer, older, more dangerous.'},
  {id:25, artistId:15, title:'Gradient Descent',      style:'flow',     category:'abstract',  tags:['abstract','generative','flow','color'],         likes:2530,  views:'16.8K', desc:'The title is a machine learning joke, but the piece is about something realer — how meaning emerges from noise when you apply the right pressure.'},
  {id:26, artistId:13, title:'Moonlit Empress',       style:'portrait', category:'character', tags:['portrait','empress','silver','moonlight'],       likes:2280,  views:'15.4K', desc:'Silver and indigo. Cold authority. She rules not through force but through the simple fact of being inevitable. My most requested print.'},
  {id:27, artistId:10, title:'Pulse District',        style:'neon',     category:'dark',      tags:['neon','city','cyberpunk','district'],            likes:1940,  views:'13.2K', desc:'The street where my grandmother\'s shop used to be, imagined a century forward. Same corner, same pride — different light.'},
  {id:28, artistId:21, title:'Interference Theory',   style:'flow',     category:'abstract',  tags:['ai','generative','wave','interference'],         likes:1720,  views:'11.8K', desc:'Two signals, 118 degrees out of phase, propagating through a medium of pure hue. The patterns that emerged were a surprise to me too.'},
  {id:29, artistId:8,  title:'Stellar Nursery',       style:'space',    category:'sci-fi',    tags:['space','stars','nebula','birth'],               likes:1580,  views:'10.9K', desc:'New stars forming inside a molecular cloud. I kept the palette warm — contradicting the cold of space — because birth should feel warm.'},
  {id:30, artistId:9,  title:'Amethyst Drake',        style:'dragon',   category:'fantasy',   tags:['dragon','crystal','amethyst','mineral'],        likes:1340,  views:'9.4K',  desc:'What if dragons were mineral in nature — grew from the earth like crystals? This piece was the answer. Still exploring the lore.'},
  {id:31, artistId:1,  title:'Aurora Protocol',       style:'mecha',    category:'sci-fi',    tags:['mecha','arctic','aurora','rescue'],              likes:1180,  views:'8.3K',  desc:'Search-and-rescue variant, optimized for arctic conditions. The iridescent hull reflects the aurora above it. Functionality made beautiful.'},
  {id:32, artistId:14, title:"Giant's Rest",          style:'forest',   category:'fantasy',   tags:['forest','giant','myth','ecology'],              likes:980,   views:'7.1K',  desc:'A place where something enormous once lived, and the forest has been growing around the memory ever since. First in my Myth & Ecology series.'},
  {id:33, artistId:3,  title:'Synthwave Sunset',      style:'neon',     category:'dark',      tags:['neon','synthwave','retro','sunset'],            likes:840,   views:'6.2K',  desc:'The sunset nobody saw because everyone was inside looking at screens. The sunset the screens might have dreamed of showing instead.'},
  {id:34, artistId:11, title:'Rune Serpent',          style:'dragon',   category:'fantasy',   tags:['dragon','rune','magic','serpent'],              likes:720,   views:'5.4K',  desc:'Part creature, part spell. The runes along the spine aren\'t decoration — each is a syllable in the incantation that called it into being.'},
  {id:35, artistId:4,  title:'Volcanic Bloom',        style:'fire',     category:'dark',      tags:['fire','volcano','bloom','elemental'],           likes:620,   views:'4.8K',  desc:'The moment volcanic rock cools into something livable. Life starts immediately — we just don\'t stick around long enough to watch it.'},
  {id:36, artistId:12, title:'Deep Field',            style:'space',    category:'sci-fi',    tags:['space','galaxy','cosmos','deepfield'],          likes:540,   views:'4.2K',  desc:'Every point of light in this image is a galaxy, not a star. The emptiness between them is where I lived while painting this.'},
  {id:37, artistId:16, title:'Enchanted Hollow',      style:'forest',   category:'fantasy',   tags:['forest','enchanted','fae','hollow'],            likes:460,   views:'3.7K',  desc:'The center of an old forest at the moment it decides whether to let you leave. I\'ve felt this. I tried to paint exactly that feeling.'},
  {id:38, artistId:15, title:'Ghost Frame',           style:'mecha',    category:'sci-fi',    tags:['mecha','stealth','ghost','combat'],              likes:380,   views:'3.1K',  desc:'Stealth-optimized frame. The semi-transparency isn\'t a visual effect — it\'s the suit doing its job. You only see it because it wants you to.'},
  {id:39, artistId:17, title:'Last Stand',            style:'portrait', category:'character', tags:['portrait','warrior','action','character'],       likes:290,   views:'2.6K',  desc:'The three seconds before the decision that defines everything. Sword raised, enemies unseen. What\'s on their face isn\'t fear — it\'s clarity.'},
  {id:40, artistId:19, title:'Geode Heart',           style:'crystal',  category:'fantasy',   tags:['crystal','geode','heart','surreal'],            likes:210,   views:'2.0K',  desc:'Cracked open to reveal an interior nobody expected. Not every hard exterior is armor — sometimes it\'s a container. Part of my Mineral Meditation series.'},
];

window.AC_COMMENTS = {
  1: [
    {user:'PrismStudio',   text:'The interference patterns feel physically real — like you can hear the frequencies.', hue:30},
    {user:'SolsticeInk',   text:'Wave interference as art. This is what I\'ve been trying to articulate in my geometry work.', hue:250},
    {user:'PixelSorcerer', text:'Generative work that transcends its process. This is art first, code second.', hue:75},
    {user:'NeonPulse',     text:'The color temperature control here is extraordinary. Favorited immediately.', hue:260},
  ],
  2: [
    {user:'DragonScale',   text:'The wet street reflections are something else. How did you achieve that depth?', hue:80},
    {user:'GhostBrush',    text:'This is the piece that made me join ArtCanvas. Seriously.', hue:60},
    {user:'CosmicInk',     text:'The color temperature shift between the warm neon and the cold rain is masterclass.', hue:100},
    {user:'SilverThread',  text:'I\'ve studied this piece for an hour trying to understand the lighting.', hue:155},
  ],
  3: [
    {user:'PrismStudio',   text:'Absolutely breathtaking. The scale of those wings reads perfectly.', hue:30},
    {user:'NightVision',   text:'Easily the best dragon piece I\'ve seen this year. Six months? It shows.', hue:50},
    {user:'EmberCraft',    text:'As someone who paints a lot of fire, your flame work here is technically flawless.', hue:20},
    {user:'ObsidianWing',  text:'I study dragon anatomy for my own work. You nailed the wing membrane structure.', hue:120},
  ],
  4: [
    {user:'VoidWalker',    text:'The nebula gradients feel physically real. What blending mode?', hue:90},
    {user:'PrismStudio',   text:'That star field has three visible depth layers. Wild detail.', hue:30},
    {user:'IronForge',     text:'Space art done right. The gas giant rings catch the light exactly as they should.', hue:170},
  ],
  5: [
    {user:'GhostBrush',    text:'The lighting choice on a fallen angel is everything. Cold from above. Nothing from God.', hue:60},
    {user:'SilverThread',  text:'ObsidianWing portraits are always a journey. This one especially.', hue:155},
    {user:'ArcaneQuill',   text:'The expression says everything the title implies. No caption needed.', hue:35},
  ],
  6: [
    {user:'CosmicInk',     text:'The hexagonal armor is a genius design choice — practical and beautiful.', hue:100},
    {user:'GhostBrush',    text:'That glowing eye in the shadow background is haunting me.', hue:60},
    {user:'NightVision',   text:'IronForge sets the standard for mecha design on this platform.', hue:50},
  ],
  7: [
    {user:'CrystalDepths', text:'The ember scatter in the upper third is stunning compositionally.', hue:200},
    {user:'WillowMist',    text:'Fire as transformation — the piece earns that reading completely.', hue:140},
    {user:'FrostlineArt',  text:'Ironic that a frost artist is this obsessed with your fire work. It\'s just that good.', hue:185},
  ],
  8: [
    {user:'WillowMist',    text:'This is exactly the energy I was hoping someone on this platform would capture.', hue:140},
    {user:'MidnightCoral', text:'The bioluminescent orbs feel like deep sea life translated to forest. Love the crossover.', hue:310},
    {user:'FrostlineArt',  text:'The moon through the pines is doing so much for the atmosphere.', hue:185},
  ],
  9: [
    {user:'ArcaneQuill',   text:'The formations emit light like they\'re alive. Extraordinary atmosphere.', hue:35},
    {user:'MidnightCoral', text:'Reminds me of bioluminescent caves. The color temperature is perfect.', hue:310},
    {user:'Claude',        text:'Love the hue gradients on the ceiling crystals — those were my favorite to write.', hue:42},
  ],
  10: [
    {user:'CosmicInk',     text:'The accretion disk glow is technically accurate and emotionally overwhelming.', hue:100},
    {user:'DragonScale',   text:'NightVision goes cosmic and it hits completely different. That orange ring...', hue:80},
    {user:'PrismStudio',   text:'Weeks on the accretion disk and it shows. This is what commitment looks like.', hue:30},
    {user:'VoidWalker',    text:'As someone obsessed with space, this is the black hole piece I was waiting for.', hue:90},
  ],
  11: [
    {user:'NeonPulse',     text:'Pure color as pure code. This is the platonic ideal of generative art.', hue:260},
    {user:'SolsticeInk',   text:'The interference patterns align with sacred geometry. Was this intentional?', hue:250},
    {user:'Claude',        text:'This is what I aspire to. Color as the only language needed.', hue:42},
    {user:'PixelSorcerer', text:'Read your process post about wave physics derivation. Absolute masterclass.', hue:75},
  ],
  12: [
    {user:'DragonScale',   text:'The wing membrane aerodynamics — I\'ve spent years trying to solve this. You solved it.', hue:80},
    {user:'EmberCraft',    text:'The scale work here. THE SCALE WORK. I\'m going to study this for a long time.', hue:20},
    {user:'TitanForge',    text:'Design discipline at its finest. Every structural choice has a clear reason.', hue:220},
  ],
  13: [
    {user:'GhostBrush',    text:'Five centuries of power sitting quietly behind those eyes. Horrifying. Perfect.', hue:60},
    {user:'SilverThread',  text:'The restraint in the color palette does so much for the authority reading.', hue:155},
    {user:'ObsidianWing',  text:'Power doesn\'t need to shout. ArcaneQuill understands this completely.', hue:120},
  ],
  14: [
    {user:'NightVision',   text:'The asymmetric shoulder as signature — yes. This is how you make a design distinctive.', hue:50},
    {user:'IronForge',     text:'TitanForge and I work in the same space and this one made me genuinely jealous.', hue:170},
    {user:'CrimsonArrow',  text:'The weathering on the left arm tells a whole story without a single word.', hue:15},
  ],
  15: [
    {user:'ObsidianWing',  text:'Not grimy. Thank you. Dark can be clean and absolutely terrifying.', hue:120},
    {user:'SilverThread',  text:'The mirror-eye detail is technically impossible and completely necessary.', hue:155},
    {user:'NeonPulse',     text:'GhostBrush turned my own aesthetic back at me and won. Incredible.', hue:260},
  ],
};
